### ISSUE TITLE
Can't edit points

### ISSUE THREAD

**Issue by kwinkunks** [agile-geoscience/pickr#198]
Picking Evan's tooth just now I found I couldn't move points once I'd picked them. They move with the mouse, then snap back to where they were.

Probably one for @stevejpurves ... and we should re-deploy when fixed.

**Comment by stevejpurves** [comment]
a good test case. the picking code has seen a lot of change, since last
deploy.

On 14 May 2015 at 16:21, Matt Hall <notifications@github.com> wrote:

> Picking Evan's tooth just now I found I couldn't move points once I'd
> picked them. They move with the mouse, then snap back to where they were.
>
> Probably one for @stevejpurves <https://github.com/stevejpurves> ... and
> we should re-deploy when fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agile-geoscience/pickr/issues/198>.
>



-- 
españa: 622 195193
uk: 020 32 893 858
@stevejpurves
airpair{}me/stevejpurves
<http://t.signauxhuit.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg7fcFmHN8pTrfRdnPr-W3Mx_5x56dJcRf5fm60W02?t=http%3A%2F%2Fairpair.me%2Fstevejpurves%3Futm_source%3Dexpert%26utm_medium%3Demail%26utm_content%3Dsignature%26utm_campaign%3Dairpairme&si=6323770510278656&pi=45b18c87-a0de-4ffb-a1b0-2cd57cf172c6>
skype: steve.purves.home
http://www.linkedin.com/in/stevejpurves

**Comment by kwinkunks** [comment]
Seems ok now on localhost at least. Is OK in prod. Closing for now.
